import { useState } from 'react'
import { isOfflineReportPending, morningApi } from '../api'
import { STOP_FIX_AREAS } from '../types'
import type { ShiftReport, SyncState } from '../types'

type SafetyView = 'stop-fix' | 'cards'
export function SafetyStage({ report, onUpdated, onNext, onBack, onSync, nextLabel = 'Machine activity' }: { report: ShiftReport; onUpdated: (report: ShiftReport) => void; onNext: () => void; onBack: () => void; onSync: (state: SyncState) => void; nextLabel?: string }) {
  const [view, setView] = useState<SafetyView>('stop-fix')
  const [pending, setPending] = useState(false)
  const [sfNumber, setSfNumber] = useState(''); const [sfArea, setSfArea] = useState<string>(STOP_FIX_AREAS[0]); const [sfLocation, setSfLocation] = useState(''); const [sfReason, setSfReason] = useState(''); const [sfInstruction, setSfInstruction] = useState('')
  const [cardType, setCardType] = useState<'red' | 'green'>('green'); const [cardReason, setCardReason] = useState('')
  const resolved = Boolean(report.stop_fix.length || report.cards.length || report.safety_reviewed_empty)
  const run = async (work: () => Promise<ShiftReport>) => {
    setPending(true); onSync({ status: 'saving' })
    try { const updated = await work(); onUpdated(updated); onSync(isOfflineReportPending(updated.id) ? { status: 'offline', message: 'Saved on this device — will synchronize automatically.' } : { status: 'saved' }); return true }
    catch (error) { const offline = !navigator.onLine; onSync({ status: offline ? 'offline' : 'failed', message: error instanceof Error ? error.message : 'Safety change was not saved.', retry: () => void run(work) }); return false }
    finally { setPending(false) }
  }
  const addStopFix = async () => {
    if (!sfNumber.trim() || !sfLocation.trim() || !sfReason.trim() || !sfInstruction.trim()) return
    if (await run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix`, { method: 'POST', body: JSON.stringify({ number: sfNumber.trim(), area_of_concern: sfArea, location: sfLocation.trim(), reason: sfReason.trim(), instruction: sfInstruction.trim() }) }))) { setSfNumber(''); setSfLocation(''); setSfReason(''); setSfInstruction('') }
  }
  const addCard = async () => { if (cardReason.trim() && await run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/cards`, { method: 'POST', body: JSON.stringify({ card_type: cardType, reason: cardReason.trim() }) }))) setCardReason('') }
  const markEmpty = (reviewed: boolean) => run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/section-resolution`, { method: 'PATCH', body: JSON.stringify({ section: 'safety', reviewed }) }))
  return <div className="morning-stage">
    <div className="morning-safety-switch" role="tablist" aria-label="Safety record type"><button type="button" role="tab" aria-selected={view === 'stop-fix'} className={view === 'stop-fix' ? 'active' : ''} onClick={() => setView('stop-fix')}>Stop &amp; Fix</button><button type="button" role="tab" aria-selected={view === 'cards'} className={view === 'cards' ? 'active' : ''} onClick={() => setView('cards')}>Red / Green Cards</button></div>
    {view === 'stop-fix' ? <section className="morning-safety-section"><h2>Stop &amp; Fix</h2>{report.stop_fix.map(item => <div key={item.id} className="morning-entry-row"><div><strong>{item.number}</strong><div className="meta">{item.area_of_concern} · {item.location}</div><div>{item.reason}</div></div><div className="morning-entry-actions"><button disabled={pending} type="button" onClick={() => void run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status: item.status === 'open' ? 'rectified' : 'open' }) }))}>{item.status === 'open' ? 'Mark rectified' : 'Reopen'}</button><button disabled={pending} type="button" className="danger" onClick={() => { if (window.confirm('Remove this Stop & Fix record?')) void run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix/${item.id}`, { method: 'DELETE' })) }}>Remove</button></div></div>)}<div className="morning-add-form"><input aria-label="Stop & Fix number" placeholder="Stop & Fix number" value={sfNumber} onChange={e => setSfNumber(e.target.value)} /><select aria-label="Area of concern" value={sfArea} onChange={e => setSfArea(e.target.value)}>{STOP_FIX_AREAS.map(area => <option key={area}>{area}</option>)}</select><input aria-label="Location" placeholder="Machinery / area / location" value={sfLocation} onChange={e => setSfLocation(e.target.value)} /><textarea aria-label="Reason or hazard" placeholder="Reason / hazard" value={sfReason} onChange={e => setSfReason(e.target.value)} /><textarea aria-label="Instruction" placeholder="Instruction / action required" value={sfInstruction} onChange={e => setSfInstruction(e.target.value)} /><button type="button" disabled={pending} onClick={() => void addStopFix()}>Add Stop &amp; Fix</button></div></section> : null}
    {view === 'cards' ? <section className="morning-safety-section"><h2>Red / Green cards</h2>{report.cards.map(card => <div key={card.id} className="morning-entry-row"><div><span className={`morning-card-dot ${card.card_type}`} aria-hidden /><strong>{card.card_type === 'red' ? 'Red' : 'Green'}</strong><span> — {card.reason}</span></div><button disabled={pending} type="button" className="danger" onClick={() => { if (window.confirm('Remove this card?')) void run(() => morningApi<ShiftReport>(`/api/morning/reports/${report.id}/cards/${card.id}`, { method: 'DELETE' })) }}>Remove</button></div>)}<div className="morning-add-form"><div className="morning-card-toggle"><button type="button" className={cardType === 'green' ? 'morning-card-green active' : ''} onClick={() => setCardType('green')}>Green</button><button type="button" className={cardType === 'red' ? 'morning-card-red active' : ''} onClick={() => setCardType('red')}>Red</button></div><input aria-label="Card reason" placeholder="Reason" value={cardReason} onChange={e => setCardReason(e.target.value)} /><button type="button" disabled={pending} onClick={() => void addCard()}>Add card</button></div></section> : null}
    {!report.stop_fix.length && !report.cards.length ? <label className="morning-resolution"><input type="checkbox" checked={report.safety_reviewed_empty} disabled={pending} onChange={event => void markEmpty(event.target.checked)} /> Reviewed — nothing to report for Safety</label> : null}
    {!resolved ? <p className="morning-caution">Add a safety record or confirm that there is nothing to report.</p> : null}
    <div className="morning-stage-nav"><button type="button" onClick={onBack}>Back</button><button type="button" className="primary" disabled={!resolved || pending} onClick={onNext}>Next: {nextLabel}</button></div>
  </div>
}
